name: Test and deploy

on:
  push:
    branches: [ "development", "debug_pipeline", "debug_pipeline_master" ]
env:
  releasepath: 'TelegramFootballBot.App/bin/Release/net5.0/linux-x64/publish'
  dotnetversion: 5.0.x
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnetversion }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

  set-environment:
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.set-environment.outputs.env }}
    steps:
    - id: set-environment
      run: |
          if [ ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/debug_pipeline_master' }} ]
          then
            echo "env=Production" >> $GITHUB_OUTPUT
          else
            echo "env=Development" >> $GITHUB_OUTPUT
          fi
    - id: show-environment
      run: echo "${{ steps.set-environment.outputs.env }}"


  deploy:
    needs: ['test', 'set-environment']
    runs-on: ubuntu-latest
    environment: ${{ needs.set-environment.outputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.dotnetversion }}

    - name: Publish
      run: dotnet publish TelegramFootballBot.App --configuration Release --runtime linux-x64

    - name: Sheet credentials variable substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ github.workspace }}/${{ env.releasepath }}/sheetcredentials.json'
      env:
        project_id: ${{ secrets.SHEET_PROJECT_ID }}
        private_key_id: ${{ secrets.SHEET_PRIVATE_KEY_ID }}
        private_key: ${{ secrets.SHEET_PRIVATE_KEY_ID }}
        client_email: ${{ secrets.SHEET_CLIENT_EMAIL }}
        client_id: ${{ secrets.SHEET_CLIENT_ID }}
        client_x509_cert_url: ${{ secrets.SHEET_CLIENT_CERT_URL }}

    - name: App Settings Variable Substitution
      uses: microsoft/variable-substitution@v1
      with:
        files: '${{ github.workspace }}/${{ env.releasepath }}/appsettings.json'
      env:
        botToken: ${{ secrets.BOT_TOKEN }}
        googleDocSheetId: ${{ secrets.GOOGLE_DOC_SHEET_ID }}
        botOwnerChatId: ${{ secrets.BOT_OWNER_CHAT_ID }}

    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SOURCE: "/TelegramFootballBot.App/bin/Release/net5.0/linux-x64/publish/"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ vars.TARGET }}
